2018-02-10 11:43:50,439 ERROR 14164 [-/::1/-/77ms POST /api/auth/register] nodejs.TypeError: Cannot read property 'register' of undefined
    at AuthController.register (E:\jtStdio\eggT\demo1\egg-example\app\controller\auth.js:15:18)
    at Object.callFn (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:36:12

pid: 14164
hostname: SF0001367391A

2018-02-10 11:47:58,756 ERROR 12880 [-/::1/-/37ms POST /api/auth/register] nodejs.ReferenceError: result is not defined
    at AuthController.register (E:\jtStdio\eggT\demo1\egg-example\app\controller\auth.js:16:5)
    at Object.callFn (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\jtStdio\eggT\demo1\egg-example\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:36:12

pid: 12880
hostname: SF0001367391A

2018-02-10 11:47:58,796 ERROR 12880 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'repassword' in 'field list'
    at Query.Sequence._packetToError (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:65:19)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`, `repassword`) VALUES('01367392', 'jt2', '7392', '7392')
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlMessage: 'Unknown column \'repassword\' in \'field list\''
sqlState: '42S22'
index: 0
sql: 'INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`, `repassword`) VALUES(\'01367392\', \'jt2\', \'7392\', \'7392\')'
name: 'unhandledRejectionError'
pid: 12880
hostname: SF0001367391A

2018-02-10 11:48:36,082 ERROR 14888 [-/::1/-/40ms POST /api/auth/register] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'repassword' in 'field list'
    at Query.Sequence._packetToError (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:65:19)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`, `repassword`) VALUES('01367392', 'jt2', '7392', '7392')
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlMessage: 'Unknown column \'repassword\' in \'field list\''
sqlState: '42S22'
index: 0
sql: 'INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`, `repassword`) VALUES(\'01367392\', \'jt2\', \'7392\', \'7392\')'
name: 'ER_BAD_FIELD_ERRORError'
pid: 14888
hostname: SF0001367391A

2018-02-10 11:51:31,634 ERROR 8776 [-/::1/-/6ms POST /api/auth/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '01367392' for key 'jobcard'
    at Query.Sequence._packetToError (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:65:19)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`) VALUES('01367392', 'jt2', '7392')
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'01367392\' for key \'jobcard\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`) VALUES(\'01367392\', \'jt2\', \'7392\')'
name: 'ER_DUP_ENTRYError'
pid: 8776
hostname: SF0001367391A

2018-02-10 13:38:24,944 ERROR 4748 [-/::1/-/42ms POST /api/auth/register] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '01367392' for key 'jobcard'
    at Query.Sequence._packetToError (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\mysql\lib\Pool.js:199:23)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\jtStdio\eggT\demo1\egg-example\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:65:19)
    at E:\jtStdio\eggT\demo1\egg-example\node_modules\co\index.js:54:5
    sql: INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`) VALUES('01367392', 'jt2', '7392')
code: 'ER_DUP_ENTRY'
errno: 1062
sqlMessage: 'Duplicate entry \'01367392\' for key \'jobcard\''
sqlState: '23000'
index: 0
sql: 'INSERT INTO `wx_user_bak`(`jobcard`, `username`, `password`) VALUES(\'01367392\', \'jt2\', \'7392\')'
name: 'ER_DUP_ENTRYError'
pid: 4748
hostname: SF0001367391A

2018-02-10 14:23:51,551 ERROR 15340 [-/::1/-/42ms POST /api/auth/login] nodejs.TypeError: Cannot set property 'userInfo' of undefined
    at AuthController.login (E:\jtStdio\eggT\demo1\egg-example\app\controller\auth.js:51:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 15340
hostname: SF0001367391A

2018-02-10 14:24:25,690 ERROR 15340 [-/::1/-/5ms POST /api/auth/login] nodejs.TypeError: Cannot set property 'userInfo' of undefined
    at AuthController.login (E:\jtStdio\eggT\demo1\egg-example\app\controller\auth.js:51:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 15340
hostname: SF0001367391A

